export const windows = [
    
    {
        id: 0,        
        title: 'Perfect Passive',
        type: 'Sistema de PVC',
        series: 'Serie (competidor de los sistemas de 80-90 mm)',
        profile: 'Clase de perfil 3 mm',

        profile_width: '82 mm',
        chambers: '7 cámaras en el marco, 6 en la hoja, para excelente aislamiento térmico',
        passive_insulation: 'Coeficiente Uf hasta 1.0 W/m²K, ideal para construcciones pasivas',
        acoustics: 'Hasta 47 dB',
        glass_thickness: 'Soporta vidrios de hasta 52 mm',
        sealing: 'Tres juntas para máxima protección contra polvo, viento y humedad',
        durability: 'Fabricado con PVC de alta calidad, resistente a deformaciones y decoloración',
        design: 'Disponible en varios colores y acabados, adaptable a diferentes estilos',

        // passive_insulation: 'el aislamiento térmico más alto Uf = 1,0, recomendado para casas pasivas y de ahorro energético',
        security: 'Protección integrada "ventana antirrobo""',
        comfort_life: 'Persianas integradas en el cristal, con mando electrónico o mecánico (opcional)',
        developed: 'Desarrollado y certificado por la UE',
        img: 'img/perfect_passive.jpg',
        price: 'Desde 100 €',
        slug: 'perfect-passive',
        description: 'Esta sistema es ideal para quienes buscan eficiencia energética y confort.'        
    },
    {
        id: 1,        
        title: 'Perfect Balance',
        type: 'Sistema de PVC',
        series: 'Serie (competidor de los sistemas de 80-90 mm)',
        profile: 'Clase de perfil 3 mm',

        profile_width: '76 mm',
        chambers: '6 cámaras en el marco y hoja, garantizando un excelente aislamiento térmico',
        passive_insulation: 'Alto aislamiento térmico Uf=1,2, recomendado para edificios energéticamente eficientes',
        acoustics: 'Excelente protección acústica, hasta 44 dB.',
        glass_thickness: 'Compatible con vidrios de hasta 48 mm, ideal para vidrios de alta eficiencia',
        sealing: 'Sistema de doble junta perimetral para una óptima protección contra el clima y filtraciones',
        durability: 'Hecho con PVC de alta calidad, resistente al clima, con larga vida útil y sin mantenimiento intensivo',
        design: 'Disponible en varios colores y acabados, adaptable a cualquier estilo arquitectónico',

        security: 'Protección integrada "ventana antirrobo"',
        comfort_life: 'Persianas integradas en el cristal, con mando electrónico o mecánico (opcional)',
        developed: 'Desarrollado y certificado por la UE',
        img: 'img/perfect_balance.jpg',
        price: 'Desde 100 €',
        slug: 'perfect-balance',
        description: 'El VEKA 76 Balance es una solución versátil, ideal para quienes buscan un equilibrio entre rendimiento térmico y estética.'        
    },
    {
        id: 2,        
        title: 'Perfect Elegance',
        type: 'Sistema de PVC',
        series: 'Serie (competidor de sistemas de 70-73 mm)',
        profile: 'Clase de perfil 3 mm',

        profile_width: '70 mm',
        chambers: '5 cámaras en el marco y la hoja, proporcionando un buen aislamiento térmico',
        passive_insulation: 'Alto aislamiento térmico Uf=1,2, recomendado para edificios energéticamente eficientes',
        acoustics: 'Buena protección acústica, hasta 42 dB',
        glass_thickness: 'Soporta vidrios de hasta 42 mm, permitiendo el uso de vidrios dobles o triples',
        sealing: 'Sistema de doble junta para proteger contra el viento, el agua y el polvo',
        durability: 'Fabricado con PVC de alta calidad, resistente a la intemperie y con una larga vida útil',
        design: 'Estética clásica con opciones de color y acabado para adaptarse a diferentes estilos arquitectónicos',

        // passive_insulation: 'Coeficiente Uf de hasta 1,3 W/m²K, adecuado para mejorar la eficiencia energética',
        security: 'Protección integrada "ventana antirrobo""',
        comfort_life: 'Persianas integradas en el cristal, con mando electrónico o mecánico (opcional)',
        developed: 'desarrollado y certificado por la UE',
        img: 'img/perfect_balance.jpg',
        price: 'Desde 100 €',
        slug: 'perfect-elegance',
        description: 'El VEKA Elegance 70 es ideal para proyectos que requieren una combinación de funcionalidad, eficiencia y estética tradicional.'        
    },
    {
        id: 3,        
        title: 'Perfect Energy',
        type: 'Sistema de PVC',
        series: 'Serie (competidor de sistemas de 70-73 mm)',
        profile: 'clase de perfil 2,7 mm',

        profile_width: 'Ancho de instalación de 72 mm',
        chambers: '5 cámaras para un mayor aislamiento térmico.',
        passive_insulation: 'Coeficiente Uf de hasta 1,0 W/m²K, ofreciendo mejor eficiencia energética',
        acoustics: 'Proporciona un buen aislamiento acústico, ideal para entornos urbanos',
        // glass_thickness: 'Soporta vidrios de hasta 52 mm',
        sealing: 'Sistema de doble junta para proteger contra corrientes de aire, humedad y polvo.',
        durability: 'Fabricado con materiales de alta calidad, resistentes a las condiciones climáticas y con bajo mantenimiento',
        design: 'Diseño moderno y funcional, disponible en varios colores para adaptarse a diferentes estilos arquitectónicos',

        // passive_insulation: 'Alto aislamiento (alto aislamiento térmico Uf=1,3)',
        security: 'Protección integrada "ventana antirrobo"',
        comfort_life: 'Persianas integradas en el cristal, con mando electrónico o mecánico (opcional)',
        developed: 'Desarrollado y certificado por la UE',
        img: 'img/perfect-energy.jpg',
        price: 'Desde 100 €',
        slug: 'perfect-energy',
        description: 'Los sistemas WHS by VEKA son una solución óptima para quienes buscan ventanas asequibles y de calidad, con un buen nivel de aislamiento térmico y acústico.'        
    },
    {
        id: 4,        
        title: 'Perfect Exellent',
        type: 'Sistema de PVC',
        series: '6 serie (competidor de los sistemas de 60 mm)',
        profile: 'Clase de perfil 2,7 mm',

        profile_width: 'Ancho de instalación de 60 mm',
        chambers: '3-4 cámaras, proporcionando un aislamiento térmico básico',
        passive_insulation: 'Adecuado para cumplir con los requisitos estándar de aislamiento térmico',
        acoustics: 'Proporciona un buen aislamiento acústico, ideal para entornos urbanos',
        glass_thickness: 'Soporta vidrios de hasta 32 mm',
        sealing: 'Sistema de doble junta para proteger contra corrientes de aire, humedad y polvo',
        durability: 'Fabricado con materiales de alta calidad, resistentes a las condiciones climáticas y con bajo mantenimiento',
        design: 'Diseño moderno y funcional, disponible en varios colores para adaptarse a diferentes estilos arquitectónicos',


        // passive_insulation: 'alto aislamiento (alto aislamiento térmico Uf=1,5)',
        security: 'Protección integrada "ventana antirrobo"',
        comfort_life: '',
        developed: 'Desarrollado y certificado por la UE',
        img: 'img/perfect-exellent.jpg',
        price: 'Desde 100 €',
        slug: 'perfect-exellent',
        description: 'Los sistemas WHS by VEKA son una solución óptima para quienes buscan ventanas asequibles y de calidad, con un buen nivel de aislamiento térmico y acústico.'        
    },
    {
        id: 5,        
        title: 'H8 AluStyle HI+/SI+',
        type: 'Sistemas híbridos',
        series: 'serie (categoría de sistemas 80-90 mm), unidad de doble acristalamiento encolado 48 mm, anchura de la hoja 100 mm, profundidad de instalación del marco 82 mm',
        alu: '',
        glass: 'marco y hoja con aluminio integrado en el exterior, diseño de ventana de aluminio',
        passive_glass: 'Unidad de doble acristalamiento de 48 mm, recomendada para edificios pasivos y de bajo consumo energético',
        hi_plus: 'high insulation (aislamiento térmico ultraelevado Uf = 1,1)',
        si_plus: 'sound insulation (aislamiento acústico ultra alto)',       
        security: 'protección integrada "ventana antirrobo"',
        comfort_life: 'persianas integradas en el cristal, con mando electrónico o mecánico (opcional)',
        developed: 'desarrollado y certificado por la UE',
        img: 'img/H8_AluStyle.jpg',
        price: 'Desde 120 €',
        slug: 'h8-alustyle',
        description: ''
    },
    {
        id: 6,        
        title: 'H8 AluGlass HI+/SI+',
        type: 'Sistemas híbridos',
        series: '(sistemas de categoría 80-90 mm), profundidad del marco de montaje 82 mm',
        alu: 'marco con aluminio integrado en el exterior',
        glass: 'hoja totalmente de cristal con aluminio integrado en el exterior',
        passive_glass: 'Unidad de doble acristalamiento de 48 mm, recomendada para edificios pasivos y de bajo consumo energético',
        hi_plus: 'high insulation (aislamiento térmico ultraelevado Uf = 1,1)',
        si_plus: 'sound insulation (aislamiento acústico ultra alto)',       
        security: 'protección integrada "ventana antirrobo"',
        comfort_life: 'persianas integradas en el cristal, con mando electrónico o mecánico (opcional)',
        developed: 'desarrollado y certificado por la UE',
        img: 'img/H8_AluGlass.jpg',
        price: 'Desde 120 €',
        slug: 'h8-aluglass',
        description: ''
    },
    {
        id: 7,        
        title: 'H8 Glass HI+/SI+',
        type: 'Sistemas híbridos',
        series: '(sistemas de categoría 80-90 mm), profundidad del marco de montaje 76 mm',
        alu: '',
        glass: 'hoja totalmente de cristal con aluminio integrado en el exterior, marco laminado o blanco',
        passive_glass: 'Unidad de doble acristalamiento de 48 mm, recomendada para edificios pasivos y de bajo consumo energético',
        hi_plus: 'high insulation (aislamiento térmico ultraelevado Uf = 1,1)',
        si_plus: 'sound insulation (aislamiento acústico ultra alto)',       
        security: 'protección integrada "ventana antirrobo"',
        comfort_life: 'persianas integradas en el cristal, con mando electrónico o mecánico (opcional)',
        developed: 'desarrollado y certificado por la UE',
        img: 'img/H8_AluGlass.jpg',
        price: 'Desde 120 €',
        slug: 'h8-glass',
        description: ''
    },
    {
        id: 8,        
        title: 'TH 68 A7',
        type: 'Sistemas de aluminio',
        thermal_insulation: '1.6 W/m2K',
        tightness: '',
        water_resistance: '',
        stability_winds: '',
        acoustics: '',
        durability: '',
        max_size: '2,400 * 1,100 mm',
        max_sash_width: '1,200 mm',
        max_sash_weight: '120 kg',
        install_depth: '75 mm',
        max_thikness: '51 mm',
        img: 'img/th_68_a7.jpg',
        price: 'Desde 150 €',
        slug: 'th-68-a7',
        description: ''
    },
    {
        id: 9,        
        title: 'ML 10 A 10',
        type: 'Sistemas de aluminio',
        thermal_insulation: '0.7 W/m2K',
        tightness: 'Class 4 (600 Pa)',
        water_resistance: 'Class E900 (900 Pa)',
        stability_winds: 'Class C3 (1200 Pa)',
        acoustics: '46(-1;-4) for TuTi, 44(-2;-4) for DC dB',
        durability: 'Class 3 (20,000 cycles)',
        max_size: '2,800 * 1,200 mm',
        max_sash_width: '',
        max_sash_weight: '200 kg',
        install_depth: '107 mm',
        max_thikness: '88 mm',
        img: 'img/ml_10_a_10.jpg',
        price: 'Desde 150 €',
        slug: 'ml10-a10',
        description: ''
    },
    {
        id: 10,        
        title: 'ML 8 Hi+ A8',
        type: 'Sistemas de aluminio',
        thermal_insulation: '0.88 W/m2K',
        tightness: 'Class 4 (600 Pa)',
        water_resistance: 'Class E900 (900 Pa)',
        stability_winds: 'Class C3 (1200 Pa)',
        acoustics: '46(0;-3) for TuTi, 44(-2;-4) for DC dB',
        durability: 'Class 3 (20,000 cycles)',
        max_size: '2,800 * 1,200 mm',
        max_sash_width: '1,700 mm',
        max_sash_weight: '200 kg',
        install_depth: '87 mm',
        max_thikness: '68 mm',
        img: 'img/ml_8_hi_a8.jpg',
        price: 'Desde 150 €',
        slug: 'ml8-a8',
        description: ''
    },
    {
        id: 11,
        title: "ECOSOL 70",
        type: "Sistemas correderos de PVC",
        thermal_insulation: "2.3 W/m²K",
        thickness_outside_wall: "70 mm",
        tightness: "Protección contra el polvo",
        galvanized_shaped_reinforcement: "Quadram de 1.5 mm o U de 2.0 mm",
        water_resistance: "",
        stability_winds: "",
        acoustics: "",
        durability: "",
        max_size: "",
        max_sash_width: "",
        max_sash_weight: "",
        install_depth: "70 mm",
        max_thickness: "24 mm",
        img: ["img/pvc_sliding_sys_ecosol_70_a.jpg", "img/pvc_sliding_sys_ecosol_70_c.jpg", "img/pvc_sliding_sys_ecosol_70_d.jpg", "img/pvc_sliding_sys_ecosol_70_f.jpg"],
        video:"videos/pvc_slide_system_ecosol_70.mp4",
        price: "",
        slug: "pvc-sl-sys-ecosol-70",
        description: "",
        opening_schemes: ["A (f)", "C (f)", "D (f)", "F (f)"],        
    },
    {
        id: 12,
        title: "WH DUO PORT 160 S",
        type: "Sistemas correderos de PVC",
        slide_type: "S",
        maximum_sash_weight: "160",
        width_min: "660 mm",
        width_max: "1640 mm",
        height_min: "700 mm",
        height_max: "2500 mm",
        thermal_insulation: "",
        thickness_outside_wall: "",
        tightness: "",
        galvanized_shaped_reinforcement: "",
        water_resistance: "",
        stability_winds: "",
        acoustics: "",
        durability: "",
        max_size: "",
        max_sash_width: "",
        max_sash_weight: "",
        install_depth: "",
        max_thickness: "",
        img: ["img/pvc_sliding_sys_duo_port_160_s_0.jpg", "img/pvc_sliding_sys_duo_port_160_s_1.jpg", "img/pvc_sliding_sys_duo_port_160_s_2.jpg"],
        video:"videos/pvc_slide_system_duo_port_160_s.mp4",
        price: "",
        slug: "pvc-sl-sys-duo-port-160-s",
        description: "",
        opening_schemes: "",        
    },
    {
        id: 13,
        title: "WH DUO PORT 160 Z",
        type: "Sistemas correderos de PVC",
        slide_type: "Z",
        maximum_sash_weight: "160",
        width_min: "660 mm",
        width_max: "1640 mm",
        height_min: "700 mm",
        height_max: "2500 mm",
        thermal_insulation: "",
        thickness_outside_wall: "",
        tightness: "",
        galvanized_shaped_reinforcement: "",
        water_resistance: "",
        stability_winds: "",
        acoustics: "",
        durability: "",
        max_size: "",
        max_sash_width: "",
        max_sash_weight: "",
        install_depth: "",
        max_thickness: "",
        img: ["img/pvc_sliding_sys_duo_port_160_z_0.jpg", "img/pvc_sliding_sys_duo_port_160_z_1.jpg", "img/pvc_sliding_sys_duo_port_160_z_2.jpg"],
        video:"videos/pvc_slide_system_duo_port_160_z.mp4",
        price: "",
        slug: "pvc-sl-sys-duo-port-160-z",
        description: "",
        opening_schemes: "",        
    },
    {
        id: 14,
        title: "WH DUO PORT 200 Z",
        type: "Sistemas correderos de PVC",
        slide_type: "Z",
        maximum_sash_weight: "200",
        width_min: "1100 mm",
        width_max: "1640 mm",
        height_min: "950 mm",
        height_max: "2500 mm",
        thermal_insulation: "",
        thickness_outside_wall: "",
        tightness: "",
        galvanized_shaped_reinforcement: "",
        water_resistance: "",
        stability_winds: "",
        acoustics: "",
        durability: "",
        max_size: "",
        max_sash_width: "",
        max_sash_weight: "",
        install_depth: "",
        max_thickness: "",
        img: ["img/pvc_sliding_sys_duo_port_160_z_0.jpg", "img/pvc_sliding_sys_duo_port_160_z_1.jpg", "img/pvc_sliding_sys_duo_port_160_z_2.jpg"],
        video:"videos/pvc_slide_system_duo_port_160_z.mp4",
        price: "",
        slug: "pvc-sl-sys-duo-port-200-z",
        description: "",
        opening_schemes: "",        
    },
    {
        id: 15,
        title: "WH DUO PORT PAS",
        type: "Sistemas correderos de PVC",
        slide_type: "",
        maximum_sash_weight: "200",
        width_min: "1100 mm",
        width_max: "1640 mm",
        height_min: "950 mm",
        height_max: "2500 mm",
        thermal_insulation: "",
        thickness_outside_wall: "",
        tightness: "",
        galvanized_shaped_reinforcement: "",
        water_resistance: "",
        stability_winds: "",
        acoustics: "",
        durability: "",
        max_size: "",
        max_sash_width: "",
        max_sash_weight: "",
        install_depth: "",
        max_thickness: "",
        img: ["img/pvc_slide_system_duo_port_pas_0.jpg", "img/pvc_slide_system_duo_port_pas_1.jpg", "img/pvc_slide_system_duo_port_pas_2.jpg"],
        video:"videos/pvc_slide_system_duo_port_pas.mp4",
        price: "",
        slug: "pvc-sl-sys-duo-port-pas",
        description: "",
        opening_schemes: "",        
    },
    {
        id: 16,
        title: "VEKA MOVE",
        type: "Sistemas correderos de PVC",
        width_max_whites: "4200 mm",
        width_max_coloreds: "3500 mm",
        height_max_whites: "2480 mm",
        height_max_coloreds: "2380 mm",
        width_max: "1979 mm",
        weight: "200 kg",
        slide_type: "",
        maximum_sash_weight: "",
        width_min: "",
        height_min: "",
        height_max: "",
        thermal_insulation: "",
        thickness_outside_wall: "",
        tightness: "",
        galvanized_shaped_reinforcement: "",
        water_resistance: "",
        stability_winds: "",
        acoustics: "",
        durability: "",
        max_size: "",
        max_sash_width: "",
        max_sash_weight: "",
        install_depth: "",
        max_thickness: "",
        img: "img/pvc_slide_system_veka_move_0.jpg",
        video:"videos/pvc_slide_system_veka_move.mp4",
        price: "",
        slug: "pvc-sl-sys-veka-move",
        description: "",
        opening_schemes: "",        
    },
    {
        id: 17,
        title: "VEKAMOTION 82 STANDART",
        type: "Sistemas correderos de PVC",
        width_max_whites: "",
        width_max_coloreds: "",
        height_max_whites: "",
        height_max_coloreds: "",
        height_min: "2200 mm",
        width_min_scheme_a: "2500 mm",
        width_min_scheme_k: "3500 mm",
        width_min_scheme_c: "4500 mm",
        width_min: "",
        width_max: "",
        weight: "",
        slide_type: "",
        maximum_sash_weight: "",
        height_max: "",
        thermal_insulation: "",
        thickness_outside_wall: "",
        tightness: "",
        galvanized_shaped_reinforcement: "",
        water_resistance: "",
        stability_winds: "",
        acoustics: "",
        durability: "",
        max_size: "",
        max_sash_width: "",
        max_sash_weight: "",
        install_depth: "",
        max_thickness: "",
        img: ["img/pvc_slide_system_vekamotion_82_standart_0.jpg", "img/pvc_slide_system_vekamotion_82_standart_1.jpg", "img/pvc_slide_system_vekamotion_82_standart_2.jpg", "img/pvc_slide_system_vekamotion_82_standart_3.jpg"],
        video:"videos/pvc_slide_system_vekamotion_82_standart.mp4",
        price: "",
        slug: "pvc-sl-sys-vekamotion-82-standart",
        description: "",
        opening_schemes: "",        
    },
    {
        id: 18,
        title: "VEKAMOTION 82 MAX",
        type: "Sistemas correderos de PVC",
        width_max_whites: "",
        width_max_coloreds: "",
        height_max_whites: "",
        height_max_coloreds: "",
        height_min: "2200 mm",
        width_min_scheme_a: "2500 mm",
        width_min_scheme_k: "3500 mm",
        width_min_scheme_c: "4500 mm",
        width_min: "",
        width_max: "",
        weight: "",
        slide_type: "",
        maximum_sash_weight: "",
        height_max: "",
        thermal_insulation: "",
        thickness_outside_wall: "",
        tightness: "",
        galvanized_shaped_reinforcement: "",
        water_resistance: "",
        stability_winds: "",
        acoustics: "",
        durability: "",
        max_size: "",
        max_sash_width: "",
        max_sash_weight: "",
        install_depth: "",
        max_thickness: "",
        img: ["img/pvc_slide_system_vekamotion_82_max_0.jpg", "img/pvc_slide_system_vekamotion_82_max_1.jpg", "img/pvc_slide_system_vekamotion_82_max_2.jpg"],
        video:"videos/pvc_slide_system_vekamotion_82_standart.mp4",
        price: "",
        slug: "pvc-sl-sys-vekamotion-82-max",
        description: "",
        opening_schemes: "",        
    }   
];
